### ISSUE TITLE
Add 'ms-python.vscode-pylance' to devContainer.json

### ISSUE THREAD

**Issue by aeschli** [luabud/hello-vscodespaces#6]
[devcontainer.json](https://github.com/luabud/hello-vscodespaces/blob/c440a9de3b970bf6b6aeaf934aaafe7e5e9ef4b6/.devcontainer/devcontainer.json) should list "ms-python.vscode-pylance" as extension. 
Codespaces will then install the extension when initializing and the user is no longer prompted

**Comment by aeschli** [comment]
FYI @luabud. Also see https://github.com/microsoft/vscode-python/issues/14850

**Comment by luabud** [comment]
Thanks for bringing this up, this is now fixed.
